version: "3.7"

name: pwe

# How to start on MAC OS
# static
# MY_IP="$(for i in {0..10}; do ipconfig getifaddr en${i}; done | head -1)" COMPOSE_PROFILES="static" docker compose up --build --remove-orphans
# generic
# MY_IP="$(for i in {0..10}; do ipconfig getifaddr en${i}; done | head -1)" COMPOSE_PROFILES="generic" docker compose up --build --remove-orphans

services:
  database:
    image: ${DB_DRIVER:-mariadb}:latest
    restart: unless-stopped
    profiles:
      - generic
    volumes:
      - mariadb:/var/lib/mysql
      #  - mysql:/var/lib/mysql
      #  - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - env_database.env
    # ports:
    #   # mysql -upwe -ppwe -P 7775 -h 127.0.0.1 pwe
    #   - "${DATABASE_PUB_PORT:-7775}:${DB_PORT:-3306}"

  fcgi:
    image: kukam/pwe:latest
    restart: unless-stopped
    #  restart: always
    depends_on:
      - database
    deploy:
      replicas: 3
    profiles:
      - static
      - generic
    stdin_open: true
    tty: true
    env_file:
      - env_common.env
      - env_${COMPOSE_PROFILES:-unknown}.env
    volumes:
      - /Users/kukam/Workspace/pwe/pwe:/PWE # Devel PWE
      - uploadfile:/PWE/webapps/generic_web/uploadfile
      - /etc/localtime:/etc/localtime:ro

  webproxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - fcgi
    profiles:
      - static
      - generic
    stdin_open: true
    tty: true
    configs:
      - source: nginx_config
        target: /etc/nginx/default.conf.template
        uid: "root"
        gid: "root"
        mode: 640
    environment:
      MY_IP: ${MY_IP:-unknown}
      COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
    command: /bin/bash -c 'eval "cat <<< \"$(</etc/nginx/default.conf.template)\"" > /etc/nginx/conf.d/default.conf && sleep 2 && nginx -g "daemon off;"'
    ports:
      - "${WEBSERVER_PUB_PORT:-7778}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # devops:
  #   image: kukam/devops:main
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - host
  #   profiles:
  #     - static
  #     - generic
  #   environment:
  #     COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

volumes:
  uploadfile: # folder for uploadfile
  mysql:      # MySQL volume
  mariadb:    # MariaDB volume
  postgres:   # Postgres volume

configs:
  nginx_config:
    file: ./default-nginx.conf

networks:
  default:
    driver: bridge
  host:
    name: host
    external: true
