version: "3"

name: pwe

# docker compose up -d --build --remove-orphans

services:
  database:
    image: ${DB_DRIVER:-mariadb}:latest
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
      #  - mysql:/var/lib/mysql
      #  - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD:-root123}
      MYSQL_DATABASE: ${DB_NAME:-pwe}
      MYSQL_USER: ${DB_USER:-pwe}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD:-pwe}
      POSTGRES_DB: ${DB_NAME:-pwe}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD:-pwe}
      POSTGRES_USER: ${DB_USER:-pwe}
    # ports:
    #   # mysql -upwe -ppwe -P 7775 -h 127.0.0.1 pwe
    #   - "${DATABASE_PUB_PORT:-7775}:${DB_PORT:-3306}"

  fcgi:
    image: kukam/pwe:latest
    restart: unless-stopped
    #  restart: always
    depends_on:
      - database
    deploy:
      replicas: 2
    stdin_open: true
    tty: true
    environment:
      FCGI_SOCKET_PATH: :7779
      PWE_CONF_pwe_home: /PWE/webapps/generic_web
      PWE_CONF_pwe_save_opt_to: db
      PWE_CONF_pwe_assets_dir: assets/, uploadfile/
      PWE_CONF_pwe_upload_dir: uploadfile/
      PWE_CONF_pwe_assets_browse_dir: uploadfile/
      PWE_CONF_pwe_opts_dir: sessions/
      PWE_CONF_dbi_db1_dbdriver: ${DB_DRIVER:-mariadb}
      PWE_CONF_dbi_db1_host: database
      PWE_CONF_dbi_db1_port: ${DB_PORT:-3306}
      #  PWE_CONF_dbi_db1_port: ${DB_PORT:-5432}
      PWE_CONF_dbi_db1_schema: public
      PWE_CONF_dbi_db1_database: ${DB_NAME:-pwe}
      PWE_CONF_dbi_db1_login: ${DB_USER:-pwe}
      PWE_CONF_dbi_db1_password: ${DB_USER_PASSWORD:-pwe}
      PWE_CONF_dbi_db1_dbversion_file: conf/${DB_DRIVER:-mariadb}_dbversion.pl
      PWE_CONF_dbi_db1_trayconnect: 10
      PWE_CONF_log_logout: STDERR
      PWE_CONF_log_loglevel: 1
      PWE_CONF_log_log_delay: 1
      PWE_CONF_log_log_delay_minimum: 0.1
    volumes:
      - /Users/kukam/Workspace/pwe/pwe:/PWE # Devel PWE
      - uploadfile:/PWE/webapps/generic_web/uploadfile
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "${FCGI_PUB_PORT:-7779}:7779"

  webproxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - fcgi
    stdin_open: true
    tty: true
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
        uid: "root"
        gid: "root"
        mode: 640
    ports:
      - "${WEBSERVER_PUB_PORT:-7778}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # webproxy-debug:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   # networks:
  #   #   - host
  #   configs:
  #     - source: nginx_config_devel
  #       target: /etc/nginx/conf.d/default.conf
  #       uid: "root"
  #       gid: "root"
  #       mode: 640
  #   ports:
  #     - "${WEBSERVER_DEVEL_PUB_PORT:-7777}:80"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

  debug:
    image: ubuntu:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  uploadfile: # folder for uploadfile
  mysql:      # MySQL volume
  mariadb:    # MariaDB volume
  postgres:   # Postgres volume

configs:
  nginx_config:
    file: ./default-nginx.conf
  # nginx_config_devel:
  #   file: ./default-nginx-debug.conf

# networks:
#   host:
#     name: host
#     external: true
