configMaps:
  nginx-fcgi-config:
    data:
      default.conf: |-
        server {
          listen   80;
          location / {
              gzip off;
              #fastcgi_keep_conn on;
              fastcgi_pass pwe_balancer;
              fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
              include fastcgi_params;
          }
          error_log /dev/stdout info;
          access_log /dev/stdout;
        }
        upstream pwe_balancer {
            server 127.0.0.1:7779;
        }

deployments:
  fcgi:
    replicas: 3
    containers:
      - name: fcgi
        image: kukam/pwe
        imageTag: latest
        imagePullPolicy: IfNotPresent
        env:
          - name: FCGI_SOCKET_PATH
            value: ":7779"
          - name: PWE_CONF_pwe_home
            value: "/PWE/webapps/static_web"
        volumeMounts:
          - name: upload-fcgi-dir
            mountPath: /PWE/webapps/static_web/uploadfile
          - name: ramdisk-fcgi-dir
            mountPath: /PWE/webapps/static_web/ramdisk
          - name: logs-fcgi-dir
            mountPath: /PWE/webapps/static_web/log
      - name: nginx
        image: nginx
        imageTag: latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: nginx-fcgi-config
            mountPath: /etc/nginx/conf.d
          - name: logs-fcgi-dir
            mountPath: /var/log/nginx

    volumes:
      - name: nginx-fcgi-config
        type: configMap
      - name: upload-fcgi-dir
        type: pvc
      - name: ramdisk-fcgi-dir
        type: emptyDir
        sizeLimit: 10Mi
        medium: Memory
      - name: logs-fcgi-dir
        type: emptyDir
        sizeLimit: 10Mi
        medium: Memory

pvcs:
  upload-fcgi-dir:
    accessModes:
    - ReadWriteMany
    size: 1Gi

services:
  nginx-svc:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80

ingresses:
  pwe.kube.freebox.cz:
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
    - paths:
      - serviceName: nginx-svc
        servicePort: http

