version: "3.7"

name: pwe

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    profiles:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/env_postgres.env
    ports:
      - "${DATABASE_PUB_PORT:-7775}:5432"

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    profiles:
      - mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/env_mariadb.env
    ports:
      - "${DATABASE_PUB_PORT:-7776}:3306"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    profiles:
      - mysql
    volumes:
      - mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/env_mysql.env
    ports:
      - "${DATABASE_PUB_PORT:-7777}:3306"

  fcgi:
    image: kukam/pwe:latest
    restart: unless-stopped
    deploy:
      replicas: 3
    profiles:
      - static
      - mysql
      - mariadb
      - postgres
    stdin_open: true
    tty: true
    env_file:
      - ./LXC/env_common.env
      - ./LXC/env_${COMPOSE_PROFILES:-unknown}.env
    volumes:
      - /Users/kukam/Workspace/pwe/pwe:/PWE # Devel PWE
      - uploadfile:/PWE/webapps/${COMPOSE_PROFILES:-unknown}_web/uploadfile
      - sessions:/PWE/webapps/${COMPOSE_PROFILES:-unknown}_web/sessions
      - /etc/localtime:/etc/localtime:ro

  webproxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - fcgi
    profiles:
      - static
      - mysql
      - mariadb
      - postgres
    stdin_open: true
    tty: true
    configs:
      - source: nginx_config
        target: /etc/nginx/default.conf.template
        uid: "root"
        gid: "root"
        mode: 640
    environment:
      MY_IP: ${MY_IP:-unknown}
      COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
    command: /bin/bash -c 'eval "cat <<< \"$(</etc/nginx/default.conf.template)\"" > /etc/nginx/conf.d/default.conf && sleep 2 && nginx -g "daemon off;"'
    ports:
      - "${WEBSERVER_PUB_PORT:-7778}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # for debuging:
  #   image: kukam/devops:main
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - host
  #   profiles:
  #     - static
  #     - generic
  #   environment:
  #     COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

volumes:
  uploadfile: # folder for uploadfile
  sessions:   # folder for sessions
  mysql:      # MySQL volume
  mariadb:    # MariaDB volume
  postgres:   # Postgres volume

configs:
  nginx_config:
    file: ./LXC/default-nginx.conf

networks:
  default:
    driver: bridge
  host:
    name: host
    external: true
