version: "3.7"

name: pwe

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    profiles:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/docker-compose_postgres.env
    ports:
      - "${DATABASE_PUB_PORT:-7775}:5432"

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    profiles:
      - mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/docker-compose_mariadb.env
    ports:
      - "${DATABASE_PUB_PORT:-7776}:3306"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    profiles:
      - mysql
    volumes:
      - mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./LXC/docker-compose_mysql.env
    ports:
      - "${DATABASE_PUB_PORT:-7777}:3306"

  fcgi:
    image: kukam/pwe-${COMPOSE_PROFILES:-unknown}:latest
    restart: unless-stopped
    deploy:
      replicas: 3
    profiles:
      - static
      - mysql
      - mariadb
      - postgres
    stdin_open: true
    tty: true
    environment:
      PWE_PROFILE: ${COMPOSE_PROFILES:-unknown}
    env_file:
      - ./LXC/docker-compose_common.env
      - ./LXC/docker-compose_${COMPOSE_PROFILES:-unknown}.env
    volumes:
      - ${PWD}:/PWE # Devel PWE
      - uploadfile:/PWE/examples/static_web/uploadfile
      - uploadfile:/PWE/examples/generic_web/uploadfile
      - sessions:/PWE/examples/static_web/sessions
      - sessions:/PWE/examples/generic_web/sessions
      - /etc/localtime:/etc/localtime:ro

  webproxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - fcgi
    profiles:
      - static
      - mysql
      - mariadb
      - postgres
    configs:
      - source: nginx_config
        target: /etc/nginx/default.conf.template
        uid: "root"
        gid: "root"
        mode: 640
    environment:
      MY_IP: ${MY_IP:-unknown}
      COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
    command: /bin/bash -c 'eval "cat <<< \"$(</etc/nginx/default.conf.template)\"" > /etc/nginx/conf.d/default.conf && sleep 2 && nginx -g "daemon off;"'
    ports:
      - "${WEBSERVER_PUB_PORT:-7778}:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # debuging:
  #   image: kukam/devops:main
  #   restart: unless-stopped
  #   stdin_open: true
  #   tty: true
  #   # networks:
  #   #   - host
  #   profiles:
  #     - static
  #     - mysql
  #     - mariadb
  #     - postgres
  #   environment:
  #     COMPOSE_PROFILES: ${COMPOSE_PROFILES:-unknown}
  #   env_file:
  #     - ./LXC/docker-compose_common.env
  #     - ./LXC/docker-compose_${COMPOSE_PROFILES:-unknown}.env
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

volumes:
  uploadfile: # folder for uploadfile
  sessions:   # folder for sessions
  mysql:      # MySQL volume
  mariadb:    # MariaDB volume
  postgres:   # Postgres volume

configs:
  nginx_config:
    file: ./LXC/docker-compose_nginx.conf

networks:
  default:
    driver: bridge
  host:
    name: host
    external: true
