


db:
  replicaCount: 1
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: db
    type: NodePort
    port: 3306
    targetPort: 3306

pwe:
  replicaCount: 3
  fcgi:
    image:
      repository: kukam/pwe
      tag: latest
      pullPolicy: IfNotPresent
  http:
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    service:
      name: http
      type: NodePort
      port: 80
      targetPort: 80
