# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: claim
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-pvc
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany #  must be the same as PersistentVolume
#   resources:
#     requests:
#       storage: 50Mi