apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  selector:
    app: db
  type: {{ .Values.db.service.type }}
  ports:
    - protocol: {{ .Values.db.service.protocol | default "TCP" }}
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pwe.http.service.name }}
spec:
  selector:
    app: pwe
  type: {{ .Values.pwe.http.service.type }}
  ports:
    - protocol: {{ .Values.pwe.http.service.protocol | default "TCP" }}
      port: {{ .Values.pwe.http.service.port }}
      targetPort: {{ .Values.pwe.http.service.targetPort }}
